spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javaquiz?currentSchema=camunda
    username: test
    password: 111
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: all